import {
  createWorksheetMazeActivity,
  type WorksheetMazeActivityDefinition,
  type WorksheetMazeSentenceGroup,
} from '../activity-kit/createWorksheetMazeActivity'

const debateSentenceGroups: WorksheetMazeSentenceGroup[] = [
  {
    id: 'debate-order',
    title: '토론 순서',
    accentColor: '#ca6b42',
    softColor: 'rgba(202, 107, 66, 0.11)',
    template: ['토론은 ', ' - ', ' - ', ' - ', ' 순서로 진행된다.'],
    blanks: [
      { id: 'order-1', answer: '주장 펼치기', widthCh: 8 },
      { id: 'order-2', answer: '반론하기', widthCh: 6 },
      { id: 'order-3', answer: '주장 다지기', widthCh: 8 },
      { id: 'order-4', answer: '판정하기', widthCh: 6 },
    ],
  },
  {
    id: 'debate-claim',
    title: '주장 펼치기',
    accentColor: '#347c6c',
    softColor: 'rgba(52, 124, 108, 0.11)',
    template: [
      '자신의 주장과, 주장을 ',
      '하는 ',
      ', ',
      '를 말한다. 이유는 그렇게 주장하는 ',
      '을 말하고, 근거는 이유를 뒷받침하는 ',
      '인 자료를 말한다.',
    ],
    blanks: [
      { id: 'claim-1', answer: '뒷받침', widthCh: 6 },
      { id: 'claim-2', answer: '이유', widthCh: 4 },
      { id: 'claim-3', answer: '근거', widthCh: 4 },
      { id: 'claim-4', answer: '까닭', widthCh: 4 },
      { id: 'claim-5', answer: '객관적', widthCh: 5 },
    ],
  },
  {
    id: 'debate-rebuttal',
    title: '반론하기',
    accentColor: '#5f6eb0',
    softColor: 'rgba(95, 110, 176, 0.11)',
    template: ['상대의 ', '에 맞서고, 이유나 근거의 ', '을 짚으며, 반론이 ', ' 않음을 밝힌다.'],
    blanks: [
      { id: 'rebuttal-1', answer: '주장', widthCh: 4 },
      { id: 'rebuttal-2', answer: '허점', widthCh: 4 },
      { id: 'rebuttal-3', answer: '타당하지', widthCh: 6 },
    ],
  },
  {
    id: 'debate-strengthen',
    title: '주장 다지기',
    accentColor: '#a45d96',
    softColor: 'rgba(164, 93, 150, 0.11)',
    template: ['우리 측 입장을 다시 한번 ', '하고, 상대측 반론을 ', '해 타당성을 높인다.'],
    blanks: [
      { id: 'strengthen-1', answer: '강조', widthCh: 4 },
      { id: 'strengthen-2', answer: '반영', widthCh: 4 },
    ],
  },
  {
    id: 'debate-judge',
    title: '판정하기',
    accentColor: '#c58a2b',
    softColor: 'rgba(197, 138, 43, 0.11)',
    template: ['판정 ', '에 따라 양측을 객관적으로 ', '하고 판정한다.'],
    blanks: [
      { id: 'judge-1', answer: '기준', widthCh: 4 },
      { id: 'judge-2', answer: '평가', widthCh: 4 },
    ],
  },
]

const debateMazeDefinition: WorksheetMazeActivityDefinition = {
  manifest: {
    id: 'debate-procedure-maze',
    title: '토론 절차 활동지와 미로',
    shortLabel: '토론 미로',
    icon: 'TM',
    color: '#c46233',
    softColor: '#f2dfd2',
    preview: 'line-match-history',
  },
  sectionType: 'quiz',
  stage: {
    title: '토론의 절차와 규칙',
    subtitle: '문장을 완성하고 정답 순서대로 미로를 이어 가는 활동',
    progressLabel: '1 / 1',
  },
  worksheet: {
    sentenceGroups: debateSentenceGroups,
    mazeRows: [
      ['출발', '주', '정', '참', '받', '침', '이', '훈', '객', '관', '적', '참'],
      ['서', '장', '독', '대', '뒷', '먹', '유', '민', '닭', '발', '주', '민'],
      ['유', '펼', '쳐', '서', '기', '다', '근', '거', '까', '민', '장', '허'],
      ['기', '치', '과', '훈', '하', '장', '다', '시', '수', '언', '선', '점'],
      ['반', '함', '주', '의', '정', '판', '조', '강', '지', '하', '당', '타'],
      ['론', '하', '기', '조', '가', '기', '반', '장', '이', '요', '나', '라'],
      ['허', '리', '주', '장', '다', '지', '영', '기', '준', '평', '가', '도착'],
    ],
    answerPath: [
      [0, 1],
      [1, 1],
      [2, 1],
      [3, 1],
      [3, 0],
      [4, 0],
      [5, 0],
      [5, 1],
      [5, 2],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
      [5, 5],
      [4, 5],
      [4, 4],
      [3, 4],
      [2, 4],
      [1, 4],
      [0, 4],
      [0, 5],
      [0, 6],
      [1, 6],
      [2, 6],
      [2, 7],
      [2, 8],
      [1, 8],
      [0, 8],
      [0, 9],
      [0, 10],
      [1, 10],
      [2, 10],
      [2, 11],
      [3, 11],
      [4, 11],
      [4, 10],
      [4, 9],
      [4, 8],
      [4, 7],
      [4, 6],
      [5, 6],
      [6, 6],
      [6, 7],
      [6, 8],
      [6, 9],
      [6, 10],
    ],
    quizGuide: '1회 오답은 초성, 2회 오답은 첫 글자가 보입니다.',
    quizInitialMessage: '문장을 모두 완성하면 아래 미로가 열립니다.',
    quizSuccessMessage: '문장을 모두 완성했어요. 이제 미로에서 순서를 직접 찾아 보세요.',
    retryMessage: '완성되지 않은 칸만 비웠어요.',
    mazeLockedGuide:
      '퀴즈를 모두 맞히면 출발부터 도착까지 정답 순서대로 칸을 눌러 길을 만들 수 있어요.',
    mazeUnlockedGuide: '다음 칸은 표시되지 않습니다. 정답 순서를 떠올리며 눌러 보세요.',
    mazeLockedMessage: '아직 미로가 잠겨 있습니다.',
    mazeCompletedMessage: '미로를 모두 완성했어요.',
    celebrationTitle: '미로 탈출 성공',
    celebrationMessage: '모든 정답을 찾아 미로를 완성했습니다.',
    gradeButtonLabel: '채점',
    retryButtonLabel: '오답 비우기',
    resetMazeButtonLabel: '미로 처음부터',
    restartAllButtonLabel: '처음부터 다시 하기',
    startLabel: '출발',
    endLabel: '도착',
    storageKeyPrefix: 'activity:debate-procedure-maze',
  },
}

const debateProcedureMazeActivity = createWorksheetMazeActivity(debateMazeDefinition)

export const debateProcedureMazeManifest = debateProcedureMazeActivity.manifest
export const DebateProcedureMazeActivity = debateProcedureMazeActivity.Component
