import {
  createWorksheetMazeActivity,
  type WorksheetMazeActivityDefinition,
  type WorksheetMazeSentenceGroup,
} from '../activity-kit/createWorksheetMazeActivity'

const electionSentenceGroups: WorksheetMazeSentenceGroup[] = [
  {
    id: 'election-law',
    title: '대표의 기준',
    accentColor: '#9f5b3d',
    softColor: 'rgba(159, 91, 61, 0.11)',
    template: [
      '선거로 뽑힌 대표는 국민의 행복한 삶과 미래를 위해 나라의 중요한 일을 결정하고, ',
      '과 ',
      '에 따라 일합니다.',
    ],
    blanks: [
      { id: 'law-1', answer: '헌법', widthCh: 4 },
      { id: 'law-2', answer: '법률', widthCh: 4 },
    ],
  },
  {
    id: 'election-sovereignty',
    title: '국민의 힘',
    accentColor: '#3b7b73',
    softColor: 'rgba(59, 123, 115, 0.11)',
    template: [
      '',
      '은 나라의 중요한 일을 결정하는 최고의 권력인 주권이 국민에게 있는 것을 의미합니다.',
    ],
    blanks: [{ id: 'sovereignty-1', answer: '국민 주권', widthCh: 7 }],
  },
  {
    id: 'election-democracy',
    title: '선거의 바탕',
    accentColor: '#476ab5',
    softColor: 'rgba(71, 106, 181, 0.11)',
    template: ['선거는 ', ' 국가에서 국민 주권을 실현하는 가장 기본적이고 중요한 방법입니다.'],
    blanks: [{ id: 'democracy-1', answer: '민주주의', widthCh: 5 }],
  },
  {
    id: 'election-vote',
    title: '한 표의 가치',
    accentColor: '#a55f8c',
    softColor: 'rgba(165, 95, 140, 0.11)',
    template: ['국민은 선거에 적극적으로 참여하여 ', '를 행사해야 합니다.'],
    blanks: [{ id: 'vote-1', answer: '소중한 한 표', widthCh: 8 }],
  },
  {
    id: 'election-recount',
    title: '다시 확인',
    accentColor: '#c7872d',
    softColor: 'rgba(199, 135, 45, 0.11)',
    template: [
      '선거의 개표 결과를 두고서 잘못이나 실수가 있는지 확인하기 위해 개표한 것을 직접 다시 검사하는 것을 ',
      '라고 합니다.',
    ],
    blanks: [{ id: 'recount-1', answer: '재검표', widthCh: 5 }],
  },
  {
    id: 'election-region',
    title: '대표의 역할',
    accentColor: '#4d7f44',
    softColor: 'rgba(77, 127, 68, 0.11)',
    template: [
      '선거로 뽑힌 대표가 ',
      '을 위해 열심히 일하면 지역이 변화하고 사람들이 더 살기 좋은 환경에서 생활할 수 있습니다.',
    ],
    blanks: [{ id: 'region-1', answer: '지역 발전', widthCh: 6 }],
  },
  {
    id: 'election-politics',
    title: '한 표의 영향',
    accentColor: '#7e5cc2',
    softColor: 'rgba(126, 92, 194, 0.11)',
    template: ['단 한 표 차이로 선거의 결과가 달라질 수 있으며, ', '도 달라질 수 있습니다.'],
    blanks: [{ id: 'politics-1', answer: '정치', widthCh: 4 }],
  },
  {
    id: 'election-smart-crosswalk',
    title: '생활 속 선거',
    accentColor: '#2d759b',
    softColor: 'rgba(45, 117, 155, 0.11)',
    template: [
      '',
      ' 횡단보도: 교통 상황을 실시간으로 파악하고, 인공지능 카메라와 감지기가 보행자의 움직임을 인식해 보행자와 운전자의 안전을 지켜 주는 교통안전 시스템.',
    ],
    blanks: [{ id: 'smart-1', answer: '스마트', widthCh: 5 }],
  },
]

const electionMazeDefinition: WorksheetMazeActivityDefinition = {
  manifest: {
    id: 'election-importance-maze',
    subject: '사회',
    title: '선거 중요성 미로',
    shortLabel: '선거 미로',
    createdAt: '2026-04-14T09:48:30+09:00',
    icon: '선',
    color: '#2f6f8f',
    softColor: '#d9ebf3',
    preview: 'line-match-history',
  },
  sectionType: 'quiz',
  stage: {
    title: '선거가 중요한 까닭',
    subtitle: '빈칸을 채우고 정답 순서대로 미로를 이어 보세요.',
    progressLabel: '1 / 1',
  },
  worksheet: {
    sentenceGroups: electionSentenceGroups,
    mazeRows: [
      ['출발', '명', '의', '표', '재', '검', '표', '희', '망'],
      ['헌', '권', '민', '한', '열', '서', '지', '노', '력'],
      ['법', '주', '주', '한', '주', '능', '역', '총', '간'],
      ['법', '민', '주', '중', '김', '무', '발', '솔', '장'],
      ['률', '국', '의', '소', '법', '정', '전', '민', '공'],
      ['내', '나', '서', '재', '숭', '치', '스', '마', '트'],
      ['사', '랑', '연', '곰', '아', '탕', '대', '구', '도착'],
    ],
    answerPath: [
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [4, 1],
      [3, 1],
      [2, 1],
      [1, 1],
      [1, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [4, 3],
      [3, 3],
      [2, 3],
      [1, 3],
      [0, 3],
      [0, 4],
      [0, 5],
      [0, 6],
      [1, 6],
      [2, 6],
      [3, 6],
      [4, 6],
      [4, 5],
      [5, 5],
      [5, 6],
      [5, 7],
      [5, 8],
    ],
    quizGuide: '1회 오답은 초성, 2회 오답은 첫 글자가 보입니다.',
    quizInitialMessage: '문장을 모두 완성하면 아래 미로가 열립니다.',
    quizSuccessMessage: '문장을 모두 완성했어요. 이제 미로에서 정답 순서를 찾아 보세요.',
    retryMessage: '완성되지 않은 칸만 비웠어요.',
    mazeLockedGuide:
      '퀴즈를 모두 맞히면 출발부터 도착까지 정답 순서대로 칸을 눌러 길을 만들 수 있어요.',
    mazeUnlockedGuide: '다음 칸은 표시되지 않습니다. 정답 순서를 떠올리며 눌러 보세요.',
    mazeLockedMessage: '아직 미로가 잠겨 있습니다.',
    mazeCompletedMessage: '미로를 모두 완성했어요.',
    celebrationTitle: '미로 탈출 성공',
    celebrationMessage: '선거가 중요한 까닭을 모두 찾아 미로를 완성했습니다.',
    gradeButtonLabel: '채점',
    retryButtonLabel: '오답 비우기',
    resetMazeButtonLabel: '미로 처음부터',
    restartAllButtonLabel: '처음부터 다시 하기',
    startLabel: '출발',
    endLabel: '도착',
    storageKeyPrefix: 'activity:election-importance-maze',
  },
}

const electionImportanceMazeActivity = createWorksheetMazeActivity(electionMazeDefinition)

export const electionImportanceMazeManifest = electionImportanceMazeActivity.manifest
export const ElectionImportanceMazeActivity = electionImportanceMazeActivity.Component
